### ISSUE TITLE
Vulnerability to absence of retiring r-spatial packages

### ISSUE THREAD

**Issue by rsbivand** [isakro/shoredate#1]
[00check.log](https://github.com/isakro/shoredate/files/11141298/00check.log)
[00install.out.txt](https://github.com/isakro/shoredate/files/11141300/00install.out.txt)
is a recent check log from running under `_SP_EVOLUTION_STATUS_=2` without retiring r-spatial packages (suggested in this package) on the library path. The minimal correction is to check that the package namespaces can be loaded, and if not, do not run those parts of the examples. It would be safer in the longer term to replace retiring r-spatial packages with active r-spatial/rspatial packages (see https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). This should resolve when https://github.com/oswaldosantos/ggsn/issues/60 is dealt with.

**Comment by rsbivand** [comment]
Please also see https://r-spatial.org/r/2023/04/10/evolution3.html, fix best by June, latest October 2023.

**Comment by isakro** [comment]
Dropped dependence on ggsn with v1.0.2, resolving this issue.
