### ISSUE TITLE
JOSS review: error in target plot

### ISSUE THREAD

**Issue by kanishkan91** [isakro/shoredate#2]
I get an error when using the `target_plot()` function as mentioned in the README. The error is as below-

Error in `st_geometry<-.sf`(`*tmp*`, value = "geom") : 
  inherits(x[[value]], "sfc") is not TRUE 

https://github.com/openjournals/joss-reviews/issues/5337

**Comment by isakro** [comment]
This should now be resolved as I have changed way the `geom` column of a `sf` object is evaluated by `target_plot()`.
