### ISSUE TITLE
JOSS review: Remove some documentation from README and add github docs

### ISSUE THREAD

**Issue by kanishkan91** [isakro/shoredate#3]
The author has put together very detailed documentation. Can they consider generating github docs based on the README? All that would be required would be to run the following-

`library(pkgdown)`
`pkgdown::build_site()`

The docs can then be linked via a URL similar to this example- https://jgcri.github.io/ambrosia/ (The github repo for this example is here- https://github.com/JGCRI/ambrosia)

OPTIONAL- The README feels heavy. The author can put some of the documentation in a vignette. pkgdown will generate separate pages for different vignettes. I would be happy to describe how this can be implemented. It is quite simple. 

https://github.com/openjournals/joss-reviews/issues/5337

**Comment by isakro** [comment]
I have been wondering about the extent of the README as well. To make the README more succinct, and as it is already repeated in the main vignette, I have therefore removed the example of how to perform and handle multiple dates from the README. 

Furthermore, as mentioned in #6, I have also added a second vignette that outlines how the package could be applied in other regions, which also demonstrates some further functionality. Finally, I have also made a `pkgdown` site hosted with GitHub Pages: isakro.github.io/shoredate/ (which was surprisingly painless to set up).
