### ISSUE TITLE
JOSS review: add guidance for other researchers wanting to make a similar pkg for another region

### ISSUE THREAD

**Issue by benmarwick** [isakro/shoredate#6]
I'm very pleased to review this high-quality software that I think is an excellent example for archaeologists to follow. Congratulations to the authors for their outstanding accomplishment. 

My only suggestion for improvement is that based on the observation that currently the package is most useful for people interested in coastal Stone Age sites in south-eastern Norway, which I expect is a rather small group. One way to increase the value and impact of the package could be to include some instructions on how another researcher could make such a package for their own region of the world.

Perhaps this could be done in a new section in the existing vignette, or maybe a new brief vignette that, using the current package as an example, shares information about the data requirements and method steps that a researcher needs to know if they want to make a similar package for another part of the world. 

https://github.com/openjournals/joss-reviews/issues/5337

**Comment by isakro** [comment]
Thank you for the good suggestion, and for taking the time to review this.

I have now added the vignette ["Applying shoredate to other regions"](https://isakro.github.io/shoredate/articles/extending-shoredate.html) (along with some additional functionality). This demonstrates ways in which this could be done, using an example from another area of Norway, and includes some pointers for how others can explore these possibilities as well. While a lot still remains to be done in terms of applicability elsewhere, especially as the method is currently only applicable in regions with a continuous sea-level fall, it is something I also intend to work on going forward.

**Comment by benmarwick** [comment]
Thanks for following up, it looks good!
