### ISSUE TITLE
Update to elevatr: Move to sf and terra

### ISSUE THREAD

**Issue by jhollist** [isakro/shoredate#8]
First, thanks for using elevatr in your package on CRAN.  Really excited that others have found it useful.

This issue is to inform you that there are some big changes coming up shortly with elevatr.  There are all around the archiving of rgdal and rgeos and the associated changes to sp and raster.  I have decided to move entirely to sf and terra and am removing dependencies to rgdal, rgeos, sp, and raster.  This has been implemented in the latest version on the main branch on GitHub (https://github.com/jhollist/elevatr).  I have not completely removed the raster dependency and elevatr is still returning a RasterLayer from get_elev_raster.  This will change in a future release and elevatr will return only sf objects for point elevation and terra SpatRasters for the elevation rasters.  Given this you will need to account for this change in your packages.  

I am planning on sending version 1.0, which still returns RasterLayer, to CRAN in a few days.  At that point I will update the GitHub version to return SpatRasters which should allow you all to test your packages.  I would expect to wait several months before sending the SpatRaster version to CRAN.

**Comment by jhollist** [comment]
Looks like one of your tests fails with the new version:

══ Failed tests ════════════════════════════════════════════════════════════════
── Failure ('test-shoreline_date.R:113:3'): finding site elevation from a raster works ──
Snapshot of code has changed:
    old                     | new                        
[3] Output                  | Output                  [3]
[4]   ===============       |   ===============       [4]
[5]   Site:  1              |   Site:  1              [5]
[6]   Elevation:  59.96235  -   Elevation:  59.96506  [6]
[7]                         |                         [7]
[8]   95% HDR:              |   95% HDR:              [8]
[9]   7010 BCE-4880 BCE     |   7010 BCE-4880 BCE     [9]

**Comment by isakro** [comment]
Thanks for both the update and elevatr! After looking through everything I believe the changes only result in a slight deviation in the snapshot from the test you posted. I'll update the snapshot once the transition has been made and keep this issue open until then in case anything else comes up.  

Mainly as a note to self: The raster object currently being returned from elevatr::get_elev_raster() is always passed to terra::rast() in the package. Running terra::rast() on an object that already is a SpatRaster does not appear to have any effect, so when elevatr is updated to return a SpatRaster, calling terra::rast() would be superfluous, but should not cause any issues.
